<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CounterFactory" targetNamespace="http://counter.com/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://counter.com/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://counter.com/bindings" location="counters_port_type_bindings.wsdl">
    </wsdl:import>
  <wsdl:service name="CounterFactoryService">
    <wsdl:port name="CounterFactoryPortTypePort" binding="binding:CounterFactoryPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
