<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AgentService" targetNamespace="http://agent.ws.cyberaide.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://agent.ws.cyberaide.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://mediator.ws.cyberaide.org/" xmlns:tns="http://agent.ws.cyberaide.org/" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://agent.ws.cyberaide.org/">
    <xs:import namespace="http://mediator.ws.cyberaide.org/"/>
    <xs:element name="checkLock" type="tns:checkLock"/>
    <xs:element name="checkLockResponse" type="tns:checkLockResponse"/>
    <xs:element name="download" type="tns:download"/>
    <xs:element name="downloadResponse" type="tns:downloadResponse"/>
    <xs:element name="exec" type="tns:exec"/>
    <xs:element name="execResponse" type="tns:execResponse"/>
    <xs:element name="fetchOutput" type="tns:fetchOutput"/>
    <xs:element name="fetchOutputResponse" type="tns:fetchOutputResponse"/>
    <xs:element name="grantAccess" type="tns:grantAccess"/>
    <xs:element name="grantAccessResponse" type="tns:grantAccessResponse"/>
    <xs:element name="listDir" type="tns:listDir"/>
    <xs:element name="listDirResponse" type="tns:listDirResponse"/>
    <xs:element name="listExecIds" type="tns:listExecIds"/>
    <xs:element name="listExecIdsResponse" type="tns:listExecIdsResponse"/>
    <xs:element name="listOutput" type="tns:listOutput"/>
    <xs:element name="listOutputResponse" type="tns:listOutputResponse"/>
    <xs:element name="listParticipants" type="tns:listParticipants"/>
    <xs:element name="listParticipantsResponse" type="tns:listParticipantsResponse"/>
    <xs:element name="listQueues" type="tns:listQueues"/>
    <xs:element name="listQueuesResponse" type="tns:listQueuesResponse"/>
    <xs:element name="listWf" type="tns:listWf"/>
    <xs:element name="listWfByType" type="tns:listWfByType"/>
    <xs:element name="listWfByTypeResponse" type="tns:listWfByTypeResponse"/>
    <xs:element name="listWfByUser" type="tns:listWfByUser"/>
    <xs:element name="listWfByUserResponse" type="tns:listWfByUserResponse"/>
    <xs:element name="listWfResponse" type="tns:listWfResponse"/>
    <xs:element name="main" type="tns:main"/>
    <xs:element name="mainResponse" type="tns:mainResponse"/>
    <xs:element name="obtainLock" type="tns:obtainLock"/>
    <xs:element name="obtainLockResponse" type="tns:obtainLockResponse"/>
    <xs:element name="remove" type="tns:remove"/>
    <xs:element name="removeResponse" type="tns:removeResponse"/>
    <xs:element name="retrieveCertificate" type="tns:retrieveCertificate"/>
    <xs:element name="retrieveCertificateResponse" type="tns:retrieveCertificateResponse"/>
    <xs:element name="statusQuery" type="tns:statusQuery"/>
    <xs:element name="statusQueryResponse" type="tns:statusQueryResponse"/>
    <xs:element name="transfer" type="tns:transfer"/>
    <xs:element name="transferResponse" type="tns:transferResponse"/>
    <xs:element name="upload" type="tns:upload"/>
    <xs:element name="uploadResponse" type="tns:uploadResponse"/>
    <xs:complexType name="obtainLock">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element name="Wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="obtainLockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="remove">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element name="Wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="removeResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listOutput">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listOutputResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByType">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element minOccurs="0" name="theType" type="ns1:wfType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByTypeResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWf">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="retrieveCertificate">
        <xs:sequence>
            <xs:element minOccurs="0" name="host" type="xs:string"/>
            <xs:element name="port" type="xs:int"/>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element minOccurs="0" name="password" type="xs:string"/>
            <xs:element name="lifetime" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="retrieveCertificateResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="download">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element name="Wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="downloadResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listExecIds">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listExecIdsResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fetchOutput">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="wfid" type="xs:int"/>
            <xs:element minOccurs="0" name="outputfile" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fetchOutputResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByUser">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByUserResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="grantAccess">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element minOccurs="0" name="userlist" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="grantAccessResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="main">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="arg0" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="mainResponse">
        <xs:sequence/>
    </xs:complexType>
    <xs:complexType name="transfer">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element minOccurs="0" name="from" type="xs:string"/>
            <xs:element minOccurs="0" name="to" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transferResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listQueues">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listQueuesResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusQuery">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusQueryResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listParticipants">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listParticipantsResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="exec">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element minOccurs="0" name="proj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="execResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="upload">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element minOccurs="0" name="aProj" type="xs:string"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element name="Wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="uploadResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listDir">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element minOccurs="0" name="dir" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listDirResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="checkLock">
        <xs:sequence>
            <xs:element minOccurs="0" name="user" type="xs:string"/>
            <xs:element name="token" type="xs:int"/>
            <xs:element name="queueId" type="xs:int"/>
            <xs:element name="Wfid" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="checkLockResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://mediator.ws.cyberaide.org/" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://mediator.ws.cyberaide.org/">
    <xs:element name="checkLock" nillable="true" type="tns:checkLock"/>
    <xs:element name="checkLockResponse" nillable="true" type="tns:checkLockResponse"/>
    <xs:element name="download" nillable="true" type="tns:download"/>
    <xs:element name="downloadResponse" nillable="true" type="tns:downloadResponse"/>
    <xs:element name="exec" nillable="true" type="tns:exec"/>
    <xs:element name="execResponse" nillable="true" type="tns:execResponse"/>
    <xs:element name="fetchOutput" nillable="true" type="tns:fetchOutput"/>
    <xs:element name="fetchOutputResponse" nillable="true" type="tns:fetchOutputResponse"/>
    <xs:element name="grantAccess" nillable="true" type="tns:grantAccess"/>
    <xs:element name="grantAccessResponse" nillable="true" type="tns:grantAccessResponse"/>
    <xs:element name="listDir" nillable="true" type="tns:listDir"/>
    <xs:element name="listDirResponse" nillable="true" type="tns:listDirResponse"/>
    <xs:element name="listExecIds" nillable="true" type="tns:listExecIds"/>
    <xs:element name="listExecIdsResponse" nillable="true" type="tns:listExecIdsResponse"/>
    <xs:element name="listOutput" nillable="true" type="tns:listOutput"/>
    <xs:element name="listOutputResponse" nillable="true" type="tns:listOutputResponse"/>
    <xs:element name="listParticipants" nillable="true" type="tns:listParticipants"/>
    <xs:element name="listParticipantsResponse" nillable="true" type="tns:listParticipantsResponse"/>
    <xs:element name="listQueues" nillable="true" type="tns:listQueues"/>
    <xs:element name="listQueuesResponse" nillable="true" type="tns:listQueuesResponse"/>
    <xs:element name="listWf" nillable="true" type="tns:listWf"/>
    <xs:element name="listWfByType" nillable="true" type="tns:listWfByType"/>
    <xs:element name="listWfByTypeResponse" nillable="true" type="tns:listWfByTypeResponse"/>
    <xs:element name="listWfByUser" nillable="true" type="tns:listWfByUser"/>
    <xs:element name="listWfByUserResponse" nillable="true" type="tns:listWfByUserResponse"/>
    <xs:element name="listWfResponse" nillable="true" type="tns:listWfResponse"/>
    <xs:element name="obtainLock" nillable="true" type="tns:obtainLock"/>
    <xs:element name="obtainLockResponse" nillable="true" type="tns:obtainLockResponse"/>
    <xs:element name="remove" nillable="true" type="tns:remove"/>
    <xs:element name="removeResponse" nillable="true" type="tns:removeResponse"/>
    <xs:element name="retrieveCertificate" nillable="true" type="tns:retrieveCertificate"/>
    <xs:element name="retrieveCertificateResponse" nillable="true" type="tns:retrieveCertificateResponse"/>
    <xs:element name="statusQuery" nillable="true" type="tns:statusQuery"/>
    <xs:element name="statusQueryResponse" nillable="true" type="tns:statusQueryResponse"/>
    <xs:element name="transfer" nillable="true" type="tns:transfer"/>
    <xs:element name="transferResponse" nillable="true" type="tns:transferResponse"/>
    <xs:element name="upload" nillable="true" type="tns:upload"/>
    <xs:element name="uploadResponse" nillable="true" type="tns:uploadResponse"/>
    <xs:complexType name="listWfByType">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element minOccurs="0" name="arg1" type="tns:wfType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="checkLockResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listOutput">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element name="arg1" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listDirResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusQueryResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="grantAccess">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element minOccurs="0" name="arg1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="checkLock">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element name="arg1" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listQueuesResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transferResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusQuery">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="retrieveCertificateResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="upload">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element name="arg1" type="xs:int"/>
            <xs:element name="arg2" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByUser">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element minOccurs="0" name="arg1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="execResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="uploadResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByUserResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="grantAccessResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="remove">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element name="arg1" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWf">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listParticipantsResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listDir">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element minOccurs="0" name="arg1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="obtainLockResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfByTypeResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fetchOutput">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element name="arg1" type="xs:int"/>
            <xs:element minOccurs="0" name="arg2" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listOutputResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="exec">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element minOccurs="0" name="arg1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="obtainLock">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element name="arg1" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="transfer">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element minOccurs="0" name="arg1" type="xs:string"/>
            <xs:element minOccurs="0" name="arg2" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="download">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
            <xs:element name="arg1" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="removeResponse">
        <xs:sequence>
            <xs:element name="return" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listParticipants">
        <xs:sequence>
            <xs:element name="arg0" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listWfResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="downloadResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fetchOutputResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listExecIdsResponse">
        <xs:sequence>
            <xs:element minOccurs="0" name="return" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listExecIds">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="retrieveCertificate">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
            <xs:element name="arg1" type="xs:int"/>
            <xs:element minOccurs="0" name="arg2" type="xs:string"/>
            <xs:element minOccurs="0" name="arg3" type="xs:string"/>
            <xs:element name="arg4" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="listQueues">
        <xs:sequence>
            <xs:element minOccurs="0" name="arg0" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="wfType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SINGLEJOB"/>
            <xs:enumeration value="KARAJAN"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="transferResponse">
    <wsdl:part name="parameters" element="tns:transferResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listDirResponse">
    <wsdl:part name="parameters" element="tns:listDirResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listParticipants">
    <wsdl:part name="parameters" element="tns:listParticipants">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="fetchOutputResponse">
    <wsdl:part name="parameters" element="tns:fetchOutputResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="execResponse">
    <wsdl:part name="parameters" element="tns:execResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listParticipantsResponse">
    <wsdl:part name="parameters" element="tns:listParticipantsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="exec">
    <wsdl:part name="parameters" element="tns:exec">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="obtainLock">
    <wsdl:part name="parameters" element="tns:obtainLock">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="transfer">
    <wsdl:part name="parameters" element="tns:transfer">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWfByUser">
    <wsdl:part name="parameters" element="tns:listWfByUser">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWfResponse">
    <wsdl:part name="parameters" element="tns:listWfResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="fetchOutput">
    <wsdl:part name="parameters" element="tns:fetchOutput">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="checkLockResponse">
    <wsdl:part name="parameters" element="tns:checkLockResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="mainResponse">
    <wsdl:part name="parameters" element="tns:mainResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listQueuesResponse">
    <wsdl:part name="parameters" element="tns:listQueuesResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="downloadResponse">
    <wsdl:part name="parameters" element="tns:downloadResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="grantAccess">
    <wsdl:part name="parameters" element="tns:grantAccess">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listExecIdsResponse">
    <wsdl:part name="parameters" element="tns:listExecIdsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="main">
    <wsdl:part name="parameters" element="tns:main">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWfByUserResponse">
    <wsdl:part name="parameters" element="tns:listWfByUserResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWfByTypeResponse">
    <wsdl:part name="parameters" element="tns:listWfByTypeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listExecIds">
    <wsdl:part name="parameters" element="tns:listExecIds">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="statusQueryResponse">
    <wsdl:part name="parameters" element="tns:statusQueryResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listOutput">
    <wsdl:part name="parameters" element="tns:listOutput">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="uploadResponse">
    <wsdl:part name="parameters" element="tns:uploadResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="statusQuery">
    <wsdl:part name="parameters" element="tns:statusQuery">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="retrieveCertificate">
    <wsdl:part name="parameters" element="tns:retrieveCertificate">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="checkLock">
    <wsdl:part name="parameters" element="tns:checkLock">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listDir">
    <wsdl:part name="parameters" element="tns:listDir">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWfByType">
    <wsdl:part name="parameters" element="tns:listWfByType">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="removeResponse">
    <wsdl:part name="parameters" element="tns:removeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="obtainLockResponse">
    <wsdl:part name="parameters" element="tns:obtainLockResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="grantAccessResponse">
    <wsdl:part name="parameters" element="tns:grantAccessResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="remove">
    <wsdl:part name="parameters" element="tns:remove">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listQueues">
    <wsdl:part name="parameters" element="tns:listQueues">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="download">
    <wsdl:part name="parameters" element="tns:download">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listWf">
    <wsdl:part name="parameters" element="tns:listWf">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="upload">
    <wsdl:part name="parameters" element="tns:upload">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="listOutputResponse">
    <wsdl:part name="parameters" element="tns:listOutputResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="retrieveCertificateResponse">
    <wsdl:part name="parameters" element="tns:retrieveCertificateResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Agent">
    <wsdl:operation name="obtainLock">
      <wsdl:input name="obtainLock" message="tns:obtainLock">
    </wsdl:input>
      <wsdl:output name="obtainLockResponse" message="tns:obtainLockResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="remove">
      <wsdl:input name="remove" message="tns:remove">
    </wsdl:input>
      <wsdl:output name="removeResponse" message="tns:removeResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listOutput">
      <wsdl:input name="listOutput" message="tns:listOutput">
    </wsdl:input>
      <wsdl:output name="listOutputResponse" message="tns:listOutputResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWfByType">
      <wsdl:input name="listWfByType" message="tns:listWfByType">
    </wsdl:input>
      <wsdl:output name="listWfByTypeResponse" message="tns:listWfByTypeResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWf">
      <wsdl:input name="listWf" message="tns:listWf">
    </wsdl:input>
      <wsdl:output name="listWfResponse" message="tns:listWfResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="retrieveCertificate">
      <wsdl:input name="retrieveCertificate" message="tns:retrieveCertificate">
    </wsdl:input>
      <wsdl:output name="retrieveCertificateResponse" message="tns:retrieveCertificateResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="download">
      <wsdl:input name="download" message="tns:download">
    </wsdl:input>
      <wsdl:output name="downloadResponse" message="tns:downloadResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listExecIds">
      <wsdl:input name="listExecIds" message="tns:listExecIds">
    </wsdl:input>
      <wsdl:output name="listExecIdsResponse" message="tns:listExecIdsResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="fetchOutput">
      <wsdl:input name="fetchOutput" message="tns:fetchOutput">
    </wsdl:input>
      <wsdl:output name="fetchOutputResponse" message="tns:fetchOutputResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWfByUser">
      <wsdl:input name="listWfByUser" message="tns:listWfByUser">
    </wsdl:input>
      <wsdl:output name="listWfByUserResponse" message="tns:listWfByUserResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="grantAccess">
      <wsdl:input name="grantAccess" message="tns:grantAccess">
    </wsdl:input>
      <wsdl:output name="grantAccessResponse" message="tns:grantAccessResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="main">
      <wsdl:input name="main" message="tns:main">
    </wsdl:input>
      <wsdl:output name="mainResponse" message="tns:mainResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="transfer">
      <wsdl:input name="transfer" message="tns:transfer">
    </wsdl:input>
      <wsdl:output name="transferResponse" message="tns:transferResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listQueues">
      <wsdl:input name="listQueues" message="tns:listQueues">
    </wsdl:input>
      <wsdl:output name="listQueuesResponse" message="tns:listQueuesResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="statusQuery">
      <wsdl:input name="statusQuery" message="tns:statusQuery">
    </wsdl:input>
      <wsdl:output name="statusQueryResponse" message="tns:statusQueryResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listParticipants">
      <wsdl:input name="listParticipants" message="tns:listParticipants">
    </wsdl:input>
      <wsdl:output name="listParticipantsResponse" message="tns:listParticipantsResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="exec">
      <wsdl:input name="exec" message="tns:exec">
    </wsdl:input>
      <wsdl:output name="execResponse" message="tns:execResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="upload">
      <wsdl:input name="upload" message="tns:upload">
    </wsdl:input>
      <wsdl:output name="uploadResponse" message="tns:uploadResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listDir">
      <wsdl:input name="listDir" message="tns:listDir">
    </wsdl:input>
      <wsdl:output name="listDirResponse" message="tns:listDirResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="checkLock">
      <wsdl:input name="checkLock" message="tns:checkLock">
    </wsdl:input>
      <wsdl:output name="checkLockResponse" message="tns:checkLockResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AgentServiceSoapBinding" type="tns:Agent">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="obtainLock">
      <soap:operation soapAction="obtainLock" style="document"/>
      <wsdl:input name="obtainLock">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="obtainLockResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="remove">
      <soap:operation soapAction="remove" style="document"/>
      <wsdl:input name="remove">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="removeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listOutput">
      <soap:operation soapAction="listOutput" style="document"/>
      <wsdl:input name="listOutput">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listOutputResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWf">
      <soap:operation soapAction="listWf" style="document"/>
      <wsdl:input name="listWf">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listWfResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWfByType">
      <soap:operation soapAction="listWfByType" style="document"/>
      <wsdl:input name="listWfByType">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listWfByTypeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="retrieveCertificate">
      <soap:operation soapAction="retrieveCertificate" style="document"/>
      <wsdl:input name="retrieveCertificate">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="retrieveCertificateResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="download">
      <soap:operation soapAction="download" style="document"/>
      <wsdl:input name="download">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="downloadResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="fetchOutput">
      <soap:operation soapAction="fetchOutput" style="document"/>
      <wsdl:input name="fetchOutput">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="fetchOutputResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listExecIds">
      <soap:operation soapAction="listExecIds" style="document"/>
      <wsdl:input name="listExecIds">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listExecIdsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listWfByUser">
      <soap:operation soapAction="listWfByUser" style="document"/>
      <wsdl:input name="listWfByUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listWfByUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="grantAccess">
      <soap:operation soapAction="grantAccess" style="document"/>
      <wsdl:input name="grantAccess">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="grantAccessResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="main">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="main">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="mainResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="transfer">
      <soap:operation soapAction="transfer" style="document"/>
      <wsdl:input name="transfer">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="transferResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listQueues">
      <soap:operation soapAction="listQueues" style="document"/>
      <wsdl:input name="listQueues">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listQueuesResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="statusQuery">
      <soap:operation soapAction="statusQuery" style="document"/>
      <wsdl:input name="statusQuery">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="statusQueryResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listParticipants">
      <soap:operation soapAction="listParticipants" style="document"/>
      <wsdl:input name="listParticipants">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listParticipantsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="exec">
      <soap:operation soapAction="exec" style="document"/>
      <wsdl:input name="exec">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="execResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="upload">
      <soap:operation soapAction="upload" style="document"/>
      <wsdl:input name="upload">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="uploadResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="checkLock">
      <soap:operation soapAction="checkLock" style="document"/>
      <wsdl:input name="checkLock">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="checkLockResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="listDir">
      <soap:operation soapAction="listDir" style="document"/>
      <wsdl:input name="listDir">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="listDirResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AgentService">
    <wsdl:port name="AgentPort" binding="tns:AgentServiceSoapBinding">
      <soap:address location="http://localhost:9090/AgentPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
